#!/bin/bash
set -e
set -f

if [[ -n "${DEPENDENCIES}" ]]; then
  apt-get remove --purge -qy ${DEPENDENCIES}
fi

apt-get -qy autoclean
apt-get -qy clean
apt-get -qy autoremove --purge

rm -rf /tmp/* /var/tmp/* /var/log/* /var/lib/apt/lists/* /var/lib/{apt,dpkg,cache,log}/* /usr/share/man/* /usr/share/locale/* /var/cache/apt/* ${CLEANUP}
find /usr/share/doc -depth -type f ! -name "copyright" -delete
find /usr/share/doc -empty -type d -delete

. ~/.profile