#!/bin/bash
#shellcheck disable=SC2016

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

ldd /usr/local/bin/ffmpeg | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'mkdir -p $(dirname /deps%); cp % /deps%;'
mv /usr/local/lib/libtensorflow* /deps/usr/local/lib
