#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

docker push miratmu/ffmpeg-tensorflow:cuda9.0
docker push miratmu/ffmpeg-tensorflow:cuda10.0
docker push miratmu/ffmpeg-tensorflow:latest
