#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

docker build --build-arg VERSION_UBUNTU=16.04 --build-arg VERSION_CUDA=9.0-cudnn7  --build-arg VERSION_LIBTENSORFLOW=1.12.0 --compress --no-cache --force-rm --squash -t miratmu/ffmpeg-tensorflow:cuda9.0  .
docker build --build-arg VERSION_UBUNTU=18.04 --build-arg VERSION_CUDA=10.0-cudnn7 --build-arg VERSION_LIBTENSORFLOW=1.15.0 --compress --no-cache --force-rm --squash -t miratmu/ffmpeg-tensorflow:cuda10.0 .
