#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

for FFMPEG_VERSION in 4.3.1 latest
do
  for CUDA_VERSION in cuda9.0 cuda10.0
  do
    docker push miratmu/ffmpeg-tensorflow:"$FFMPEG_VERSION"-"$CUDA_VERSION"
  done
done

docker push miratmu/ffmpeg-tensorflow:latest
