name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TEMPORARY_DIRECTORY: /home/runner/work/_temp
jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-18.04
    steps:
      - name: Create environment
        run: |
          echo "export DOCKER_TAG=\"${GITHUB_SHA}-$(date +'%Y%m%d-%H%M%S')\"" >> ./vars
      - name: Persist environment
        uses: actions/upload-artifact@v1
        with:
          name: environment
          path: ./vars
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: [preparation]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch environment
        uses: actions/download-artifact@v1
        with:
          name: environment
      - name: Authenticate registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Configure system
        run: script/github-configure
      - name: Build image
        run: script/github-build
      - name: Publish image
        run: script/github-publish
      - name: Test image
        run: script/github-test
