name: Pull request
on:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TEMPORARY_DIRECTORY: /home/runner/work/_temp
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: [preparation]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure system
        run: script/github-configure
      - name: Build image
        run: script/github-build
      - name: Test image
        run: script/github-test
