name: Pull request
on:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
  latest-cuda9_0:
    name: Build, CUDA 9.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure system
        run: script/github-configure latest-cuda9.0
      - name: Build image
        run: script/github-build latest-cuda9.0
  latest-cuda10_0:
    name: Build, CUDA 10.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure system
        run: script/github-configure latest-cuda10.0
      - name: Build image
        run: script/github-build latest-cuda10.0
      - name: Test image
        run: script/github-test latest-cuda10.0
